train:
  batch_size: 16
  learning_rate: 4e-4
  model_name: model.pt
  device: cpu

data:
  dataset_path: ../vggface/vggface2_crop_arcfacealign_224
  same_prob: 0.2
  img_height: 224
  img_width: 224
  norm_mean: 0.5
  norm_std: 0.5

loss:
  rec_loss_weight: 1
  attribute_loss_weight: 1
  id_loss_weight: 1
  weak_fm_loss_weight: 1
  adv_loss_weight: 0.1
  face_attribute_detector: pretrained_models/shape_predictor_68_face_landmarks.dat
  insightface_allowed_modules: ['detection', 'landmark_2d_106']
  insightface_input_size: [640, 640]

network:
  in_channels: 3
  n_channels: 64
  n_ae_depth: 4
  n_pose_info: 0
  n_iid_block: 9
  n_id_latent: 512
  discriminator:
    in_channels: 3
    n_channels: 64
    n_depth: 3
    n_discriminator: 2
    weak_fm_loss_layer_idx: [2, 3]
  arcface:
    model_path: pretrained_models/backbone.pth
